### ISSUE TITLE
BlackHole CoolDown disappeared on profile pages

### ISSUE THREAD

**Issue by AdriGeeK03** [FreekBes/improved_intra#36]
**Describe the bug**
BlackHole CoolDown disappeared on profile pages.

**To Reproduce**
Go to any user profile page

**Expected behavior**
It was expected to see a date or the remaining days of the BlackHole.

**Screenshots**
![image](https://user-images.githubusercontent.com/50402620/196457432-c7a6f711-5104-4f6e-9754-30d4eafbc9b2.png)

**HTML source code**
[Intra Profile alouis-j.html.txt](https://github.com/FreekBes/improved_intra/files/9811408/Intra.Profile.alouis-j.html.txt)

**Desktop information (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS x64
 - Tested Browser Chrome & Firefox

**Comment by FreekBes** [comment]
This has been fixed, but not by my doing. The Intra team changed the ID of the Black Hole to #modern-blackhole-date instead of #blackhole-date, overruling the CSS rule which caused this issue. This change is likely related to #37.

I do notice the old black hole countdown not appearing any more if enabled. This has been fixed in commit 3441f45 and will be rolled out in the next update of Improved Intra.
