### ISSUE TITLE
Logout after every reboot

### ISSUE THREAD

**Issue by Anarbb** [FreekBes/improved_intra#49]
**Describe the bug**
All the preferences get reset after a reboot, and when you click on the extension icon to see if it's logged out, it looks normal at first, but if you restart your internet browser it shows the "login with intra" prompt, the preferences that get reset are the blackhole timer, and dark mode switches back to light mode

**To Reproduce**
0. Be logged into the extension
1. Reboot your machine
2. Go to intra.42.fr
3. Restart the browser

**Expected behavior**
Staying logged in

**Desktop information (please complete the following information):**
 - OS: Linux/MacOS
 - Browser: Firefox

**Comment by FreekBes** [comment]
Hi there! Do you experience this issue on a cluster machine at a 42 campus, or also on your own computer?

At Codam, the issue also appears, since extensions often get reset upon logout. However, on my own computer, I do not have this issue myself - although I do not use Firefox.

**Comment by Anarbb** [comment]
Hey!

i apologize I haven't seen your message, but yes it happens in a cluster machine too, will there be any workarounds to the problem?

**Comment by FreekBes** [comment]
This might be intentional - on 42's cluster machines, the local storage of the browser is often not kept. This means that the extension will lose track of the session, causing you to authenticate yourself again. In this case, it will revert to the default settings (dark mode switch to light mode would then be because your OS is set to light mode).

Is this only happening on 42 cluster machines, or also on any of your personal device(s)? Do you have internet when the browser is launched after a reboot?

**Comment by Anarbb** [comment]
No this only happens in 42's machines, dosen't happen with my machine

**Comment by FreekBes** [comment]
Then sadly this is a problem with the 42 machines, and not with Improved Intra. Local storage of Chrome is not saved properly, it's something I'm also aware of as the Sysadmin at Codam (42 Amsterdam). Haven't found a fix yet
