### ISSUE TITLE
Using "Click to go back' on cluster visualization

### ISSUE THREAD

**Issue by GoudDeal** [FreekBes/improved_intra#54]
Upon clicking on your current workstation on your profile page, you get correctly redirected to the page showing you clusters. After that, if you click on a profile and then use the "Click to go back" arrow, the clusters do not show up correctly but instead show the raw data of the users currently logged in. The bug happens with Google Chrome on Ubuntu 22.04.1 LTS. I did not try to reproduce the bug on other OS or other browser.
![bugintra](https://user-images.githubusercontent.com/41930643/229203842-1fd4e34d-992d-4630-b09b-906767961142.png)

**Comment by FreekBes** [comment]
What browser are you using

**Comment by GoudDeal** [comment]
I forgot to mention it in the original post, I edited it now.

I am using Google Chrome on Ubuntu 22.04.1 LTS

**Comment by FreekBes** [comment]
Hi there, sorry for the late response. I'm unable to reproduce this issue locally. Possibly it's a bug in the Intranet that is not caused by the extension.

I'm assuming the JSON data in your screenshot is from the [clusters.json endpoint](https://meta.intra.42.fr/clusters.json)? The extension never requests this data. Could you check if you experience this bug also with the extension disabled?

**Comment by rabarbra** [comment]
I was able to reproduce this issue, and solution above solves it.
