### ISSUE TITLE
Cannot authenticate - Bad gateway

### ISSUE THREAD

**Issue by Sahnky** [FreekBes/improved_intra#57]
It is not possible to authenticate the extension on Chrome using our intra profile. With this, there are a few functions that are not loading and it's not possible for new users to use the extension either. The message received when trying to authenticate or access the extension home page is: "502 Bad Gateway - nginx/1.18.0"

1. Go to the extension icon.
2. Click on it and choose to authenticate.
3. A new window will appear and, after a minute, it'll show the error.

It was expected that we could access the extension configuration page and could authenticate using 42's website.

![Screenshot from 2023-07-19 20-30-52](https://github.com/FreekBes/improved_intra/assets/56981667/7a25793b-5186-4a5a-a126-2043a5659793)

**Desktop information (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Extension version: 4.1.0

**Comment by FreekBes** [comment]
Hello, thank you for the bug report.

The Improved Intra back-end server has been experiencing some crashes lately, causing issues like these every now and then for up to a few minutes. I need to know whether the crash is related to this feature, or if you're experiencing a side-effect of the crash being caused elsewhere.

Are you still experiencing this issue? If so, could you share with me the logs from the extension's Developer Tools console window? If you do not know how to open this, you can find a guide [here](https://jun711.github.io/web/how-to-turn-on-chrome-devtools-for-chrome-extension/).

**Comment by FreekBes** [comment]
Never mind, I've found the issue. It is now resolved.

As you know, the Intranet has been down frequently over the past 2 months. 42 added extra DDoS protection to their servers to prevent this. However, it seems they also blocked the Improved Intra server from accessing the API. Possibly this was caused by the server spamming requests after the API application's secret key rotated and I forgot to update the key in the environment variables.
