### ISSUE TITLE
Evaluations are hidden

### ISSUE THREAD

**Issue by EnzoDeg40** [FreekBes/improved_intra#73]
**Describe the bug**
Evaluations are hidden

**To Reproduce**
Complicated to know how this happens. It's been a long time since I've done an evaluation. When I had feedback I did not have this problem. I will try to update this issue if I have more news.

**Expected behavior**
Evaluations are hidden after loading the dark theme. In the first photo you can see the evolution very quickly before the theme loads completely.

**Screenshots**
![image](https://github.com/FreekBes/improved_intra/assets/35306710/b46afdc9-4cfe-4065-83ac-388efa07ae61)
![image](https://github.com/FreekBes/improved_intra/assets/35306710/9f7b50a7-c7ab-4bb7-9bed-97568f2a69e8)
![image](https://github.com/FreekBes/improved_intra/assets/35306710/f18ff380-a0e8-43e7-8043-4bc02900681b)
![image](https://github.com/FreekBes/improved_intra/assets/35306710/bd8aca50-dd0b-45f3-96cd-ac3570b27a43)

**HTML source code**
[edegraev.txt](https://github.com/FreekBes/improved_intra/files/14450149/edegraev.txt) (.txt cause .html not working )

**Desktop information (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Browser: Google Chrome 121.0.6167.139 (Official Build) (64-bit)
 - Current server version: 3.3.0
- Server target version: 4.2.0
- Extension version: 4.3.1

**Comment by FreekBes** [comment]
I can't think of any way this could be caused by the extension. The extension doesn't change anything regarding this list of upcoming evaluations. Instead, I'm pretty sure the evaluations are hidden because of the show/hide button being in "hidden" mode. Click "show" and they will show up and should remain showed up on a reload. This is a feature from "vanilla" Intra.

If this is not the case, feel free to reopen this issue.

**Comment by EnzoDeg40** [comment]
Wow why the hell created this button. It's probably because of that, thank you very much.
