### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by acasamit** [FreekBes/improved_intra#84]
**Describe the bug**
When i click on "Authentificate with 42" on the extention pop-up i get a blank "Internal Server Error" page, i tried with severals OS and browsers, i think this is a problem with my account

![image](https://github.com/user-attachments/assets/ae633fc3-4e47-4b08-a0ef-22d6a6b621e9)
![image](https://github.com/user-attachments/assets/4358038a-f512-4dd4-a49d-42be80fd5d26)

**HTML source code**
cannot upload html on github
![image](https://github.com/user-attachments/assets/8bc124ab-a0fa-43a5-a294-1ad13af267c2)

**Desktop information (please complete the following information):**
 - OS: Linux/windows
 - Browser: Firefox, Chrome, Opera GX

 - Extension version: cannot see due to internal server error page but i guess that's the latest version

**Comment by FreekBes** [comment]
This bug happens when the CSRF in the URL in your browser does not match the server's expected result. It is not supposed to show an error like this.

To circumvent this, when authenticating with your 42 account do not refresh the page and connect over a stable network connection. When trying again, make sure to go through the entire authentication flow again:
1. Go to iintra.freekb.es
2. Click the sign in button
3. Sign in to 42's Intranet if they ask you to, do not modify the URL
4. If 42 asks you to allow Improved Intra access to your account's details, press the 'Authorize' button
5. Wait for the process to complete (when it's complete you should see the unfinished Improved Intra homepage in your browser)

I would fix this but I simply lack the time (and motivation knowing Intra v3).

**Comment by FreekBes** [comment]
The issue has been resolved, turns out this is due to the 42 API not returning all campuses with a regular student API key. There are some hidden ones, one of which you are part of.

The back-end server tried to add this hidden campus to the database when you log in by fetching it from the API, seeing as the campus_id shows up in your user data. But the campus endpoint then claims the campus does not exist. Source code that generated this error can be found [here](https://github.com/FreekBes/improved_intra_server/blob/1e88084e5bb67e79e40540f39abc384446003f7a/src/lib/auth/users.py#L9L17).

I haven't fixed the source code and opted to add these campuses manually to the database. Might change the code later.
